__author__ = "Serditov Nikita"
__copyright__ = "Copyright 2023, ISGNeuro"
__credits__ = []
__license__ = ""
__version__ = "0.1.4"
__api_version__ = "1"
__maintainer__ = "Serditov Nikita"
__email__ = "nserditov@isgneuro.com"
__status__ = "Release"
